"""Concept lattice construction for K^r, K^f and K^c.

The paper builds full lattices, whose worst case is O(2^(|S|.|R|)). At the
experimental sizes that is impossible, so we build an *iceberg* lattice: the
extents are closed under intersection starting from the attribute extents, with
a minimum-support filter and a hard cap on the number of concepts (adjustment
A10). The builder actually used is recorded in the output file.
Author: F. Ghedass.
"""
from __future__ import annotations
import json
from pathlib import Path

import numpy as np


def build(inc: np.ndarray, min_support: int = 1, cap: int = 1200) -> list:
    """Return concepts as (extent, intent), both frozensets of indices.

    Extents are generated by closing the attribute extents under intersection,
    which is the standard way to enumerate a lattice bottom-up. We stop at `cap`
    concepts and drop extents smaller than `min_support`.
    """
    n_obj, n_att = inc.shape
    seeds = []
    for a in range(n_att):
        ext = frozenset(np.nonzero(inc[:, a])[0].tolist())
        if len(ext) >= min_support:
            seeds.append(ext)
    exts = {frozenset(range(n_obj))}          # top concept
    exts.update(seeds)
    frontier, capped = list(seeds), False
    while frontier and len(exts) < cap:
        nxt = []
        for e in frontier:
            for s in seeds:
                m = e & s
                if len(m) >= min_support and m not in exts:
                    exts.add(m)
                    nxt.append(m)
                    if len(exts) >= cap:
                        capped = True
                        break
            if capped:
                break
        frontier = nxt
    out = []
    for e in exts:
        idx = sorted(e)
        intent = frozenset(np.nonzero(inc[idx].all(axis=0))[0].tolist()) if idx else frozenset(range(n_att))
        out.append((frozenset(idx), intent))
    out.sort(key=lambda c: -len(c[0]))
    return out


def save(concepts: list, path: Path, objects: list, attributes: list, meta: dict) -> None:
    """Persist a lattice as JSON: one record per formal concept."""
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    recs = [{"id": k, "extent": [objects[i] for i in sorted(c[0])],
             "intent": [attributes[j] for j in sorted(c[1])]}
            for k, c in enumerate(concepts)]
    Path(path).write_text(json.dumps({"meta": meta, "n_concepts": len(recs),
                                      "concepts": recs}))


def locate(concepts: list, want: set):
    """Algorithm 2, line 13: concept with the largest Intent covered by F_u.

    The paper's condition is `cpt_f.Intent subset-of F_u`, so we look for the
    most specific concept whose intent stays inside the requested features.
    """
    best = None
    for ext, intent in concepts:
        if intent <= want and (best is None or len(intent) > len(best[1])
                               or (len(intent) == len(best[1]) and len(ext) > len(best[0]))):
            best = (ext, intent)
    return best
